# Clippy configuration for atlas-embeddings
# Strictest standards for peer-reviewed mathematical code

# Cognitive complexity threshold (lower = stricter)
cognitive-complexity-threshold = 15

# Documentation requirements
missing-docs-in-crate-items = true

# Avoid large types being passed by value
pass-by-value-size-limit = 128

# Function parameter limit
too-many-arguments-threshold = 5

# Maximum struct fields
struct-field-name-threshold = 20

# Literal precision
literal-representation-threshold = 16

# Array size limits (64 bytes for Vector8 which is 8 × 8-byte HalfIntegers)
array-size-threshold = 64

# Maximum line length for literals
doc-valid-idents = ["Atlas", "E6", "E7", "E8", "F4", "G2", "Dynkin", "Cartan", "Weyl"]

# Disallowed names to avoid
disallowed-names = ["foo", "bar", "baz", "tmp", "temp"]

# Single char binding names allowed in mathematical contexts (matrix entries, etc.)
single-char-binding-names-threshold = 10
