repos:
  - repo: local
    hooks:
      - id: terminology-lint
        name: terminology-lint
        entry: python tools/terminology_lint.py
        language: system
        pass_filenames: false
      - id: docs-lint
        name: docs-lint
        entry: python tools/docs_lint.py
        language: system
        pass_filenames: false
      - id: claims-guard
        name: claims-guard
        entry: python tools/claims_guard.py
        language: system
        pass_filenames: false
