[build-system]
requires = ["setuptools", "wheel"]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q"

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
ignore_missing_imports = false
strict = true
