name: AEP Decision Rules
on: [push, pull_request]
jobs:
  decision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -e . pytest numpy
      - run: pytest -q tests/test_decision_rules.py
